import Head from 'next/head';
import Footer from './components/Footer/Footer'
import Navbar from './components/Navbar/Navbar'
import { Sidebar } from './components/Sidebar/Sidebar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "RBK - Student's Space",
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
      <link rel="shortcut icon" href="/static/favicon.ico" />
    </Head>
      <body className={inter.className}>
        <Navbar />
        <Sidebar />

        <main className="lg:pl-16 pt-16">
          {children}
        </main>

        <Footer />
      </body>
    </html>
  )
}
